name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install XQuartz and X11 development libraries
    - name: Install X11
      run: |
        brew install xquartz

    # Run the install script
    - name: Run install script
      run: ./install
